dist: trusty
language: python
python:
- '2.7'
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/travis_creds.json"
  global:
  - secure: P6Qt52mIgkXLfwSkSwu7l3TOP8P0drW09rzsWimZqPgiRny1Ci8kyJAPl8YsGIwfd8/B9WF7Yjm/mY/gImPGFB7ACWKDI5qmP8JQxSh97RJeK49HujlhV97s2bbw8Fp7Esx2YMByqiCl4uVGSjM16EzmVC2NwWgFAJ6uCXleUffj+L1zUrE0I/3K1kZrGAy8/NbxCjECttuYDzyy1BcnqkX6wRfV+fGNyUFVhQRS1r/8KiQBkCKmWZ9QNrDeQ8//gpyLzAlPLqN2qdajSp0Pssr5slOfarh4TY7DHJKdocOWQKa4I+rqhjWdrofoihEV1EfqQSaupw5/2ZeR3/Wh4jrVe8jfgdQDGovcQ/FesdN3WxhzqmKW5RvRKsc0cdf0yfP/Gb8vjpwQ589RIK8/i7s5t2+roHmBAtbU6bjadnIntMfUUTaENJxwLvhCtkU0v6SYXXQ3lX1Bo/kD+pPNhTTRiCGT5AYIV9rfBZMUNUwRW7gFUB63NmPO1oot6mj3p4ZJEGoQFSD+TUY0bHkQFZsjcrdUSZ3OMrBeYMqi4OmqsZ1vqCRsCpB4ADmJXhkcKBtnznXk6+/rJhaBm8DTDd4ETjPpi10vwu4nMzJ6ww1CKyWFgTMaX05aeg67zTqd1xexcYRL0nghcLkCG8awn952V0BWLE3MDarypHzlb3k=
  - secure: Az9vfuMIVKaOo90iSWjQLSLPfMAF1g2TtN24MIcn+FEfVSXkHC3L/pp5U0cIBZVHVg7gFDHJkjIJUNaxXZ3niopl2f/HG0OPWyHJig/OdEJPW4lHQPCW5MJaZdgMWrXDCtNsBLlwOPEOf1ze6418Hrsp2SRRYPUAWAUlDqRcguANqryyAj5XjbnN3KlDSdMx/8v8ZdOB2eqj8IcykjvEgTyVlZXDYfCtRSPdSnKTt6FvPfi+cwde9JpY5ICSeq46DaeGGlyOH7Sp3guRN0S+yU5yK63otERw8WbZyMIrVIe3+fM7QxxzTEDMYLNGwCipXn/C58PFDqC3Q7RkcdXsJL7TJTOBMM8YvK76IEaSaVA7ObWo1nDFwoizWpWHr4IjGJ8KNJ4g/XztwkP91tICvZy5+R71AQ78DLRf4P5mD9s0lgLrxRlGSt4jD2x9ZXBVSrGN5g1FQbQai7PhOi2SeCDEp+HsjcmhziFTJEuV2zXlH/lVl/ArMr80cpnspuND/DBvJ2oXbbiNmKTJQfiexewK1vDN9Q1t5/XpX70rbCDMTgHjC9JLf5q/0bQ9nIhcjd1XxdwQUkKLXCEhRV/lrnUVVR6F3PcTUE2qJfJtvoK1Cwl0QaXBccwCNBW7l64ATIO82+Hp1dhIulk3Vb1Gk3FG87l9AIxNqCEmE6xL++U=
  - secure: yfHLDk1I4pllke8HRG1h/CWwn3pXtrcScpZtNvYsKc6uustaV6SfH5fBvhRQaXAEwFA+xpWrM6/56UPSpOH/hT69x0nOl3tvqGiaR4ySy0l+EDH0bLIgN//1za964d9QkOaM9gplVKu7uyEL7RbHDTdn+9/Pw9+JJBiZ/auqAQw+phdNX1VhwhUAsUJ7TLrTezBFlSVyRD7ZgpQ5w4ovIyEj4WnKb4gPZdVvYWIiMuOiBxMipIZ2xgoCDgQwwOnt4L2kt23FA7JiyaUt7VHEssNC/qVsYWdWirUM2W0M9AAySphnZ32gMKdbwhbBJgJfKl8wsPV71/kbzRsbrtXIsTfDDWZEm2k4dh9dVvx0iL7Sm/lMrYtaVgWsSvvivMEMZoGeMvQn04RWQw4NqbKoFokDY4/uaAkD9kPlSx4PU/TWHhgx1Xt5nKZ8nton3cElNhFmQOGuD269cKt8dzLzD6E8ZlzCft1CKsXBuLE6smrVkP7c/TqKgF/PaS45usm79zRpJ7nLNzxjVYHkX371u1gfxWNfX8DflgFyClRIdyAv9ts2OwvWTILj2qQijwouuvi92ZWBV6zRWfCVM0HRuVYekQOhIoUPJVymFVLcTQf3aDSnPA87hwwwT2r7CVPewEAeL5DlFG+YJNsvpRs4Vie4qPGsov3lztKcVQuzcAw=
before_install:
- openssl aes-256-cbc -K $encrypted_fb79651687f6_key -iv $encrypted_fb79651687f6_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar -xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
- echo $GCE_PROJECT_ID
install:
- pip install ansible==2.7.1 molecule==2.19.0 apache-libcloud pycrypto
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
