---
- name: Add apt-key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: EA312927
  tags: install
- name: Add MongoDB repo
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
  tags: install
- name: install MongoDB
  apt:
    name: mongodb-org
  tags: install
- name: enable MongoDB
  systemd:
    name: mongod
    enabled: true
  tags: install
